<a href="https://colab.research.google.com/github/ravikeerthi7606/Pandas/blob/main/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([2,32,12,1])

In [4]:
df

    0
0   2
1  32
2  12
3   1

In [5]:
price = pd.Series([2,32,12,1], name="Price")

In [6]:
price

0     2
1    32
2    12
3     1
Name: Price, dtype: int64

In [1]:
!unzip archive.zip

Archive:  archive.zip
  inflating: deliveries.csv
  inflating: matches.csv